Add PR source validation to Jenkinsfile
logdna/env-config-node pull request #4
Opened 2020-10-26 23:14 UTC by jakedipity

Semver: patch
Ref: LOG-7715

Signed-off-by: Jacob Hull <jacob@planethull.com>

2020-10-26 23:53 UTC, mdeltito requested changes

2020-10-26 23:53 UTC, mdeltito commented on Jenkinsfile
> +        , repo: REPO
there's one more of these, line 162

2020-10-27 18:35 UTC, jakedipity commented on Jenkinsfile
> +        , repo: REPO
fixed

2020-10-27 19:08 UTC, mdeltito submitted a review, later dismissed

2020-10-28 18:27 UTC, darinspivey approved these changes, later dismissed

2020-10-28 18:28 UTC, mdeltito commented
@logdnabot test this

2020-10-28 23:41 UTC, jakedipity commented
@logdnabot test this

2020-10-29 02:27 UTC, jakedipity commented
There appears to be an issue with Jenkins status checks... one of the status checks is hanging and Jenkins is not reporting any secondary tasks running / started / stopped

2020-10-29 04:59 UTC, jakedipity commented
@logdnabot test this

2020-10-30 18:00 UTC, jakedipity commented
@logdnabot test this

2020-10-30 18:34 UTC, mdeltito approved these changes

2020-10-30 18:34 UTC, esatterwhite approved these changes

2020-10-30 18:34 UTC, dm36 approved these changes

2020-10-30 18:37 UTC, merged